### ISSUE TITLE
Can I get your pretrained models?

### ISSUE THREAD

**Issue by dwyi84** [mcgridles/LENS#4]
I am trying to run LENS pipeline.py with your trained models.
Let me know if I can get the data.

**Comment by mcgridles** [comment]
@dwyi84 if you give me your email I can share them with you on Dropbox.

**Comment by dwyi84** [comment]
dwyi84@gmail.com
thanks a lot 😊

2020년 10월 6일 (화) 오후 10:26, Henry Gridley <notifications@github.com>님이 작성:

**Comment by nampqaime** [comment]
Hello,

@mcgridles @dwyi84  Can you share trained models with me? Thanks.
My gmail: nampq.aime@gmail.com
