### ISSUE TITLE
Library or Module For Sony IMX322 with Jetson TX2

### ISSUE THREAD

**Issue by sam-rke** [mcgridles/LENS#5]
Hi @mcgridles !!
Hope you are doing good.
Actually i need to use Sony IMX322 with Nvidia Jetson TX2 and language will be C/C++.
As per mu understanding IMX322 is a USB type of camera so i am thinking about "ffmpeg" for video recording but I am not sure which C++ library will be used to start capturing videos  over TX2.
Can you Suggest me please if there is any?
Thanks & Regards

**Comment by mcgridles** [comment]
I'm not sure I have the right background to answer this but OpenCV has a C++ implementation that can be used to capture video both directly and over a stream. It may not do exactly what you want it to do but it's a great place to start as it is very a standard and well known library in computer vision.
